FREEZING_POINT_FAHRENHEIT = 32
FAHRENHEIT_TO_CELSIUS_RATIO = 5.0 / 9
CELSIUS_TO_FAHRENHEIT_RATIO = 9.0 / 5

def ftoc(value)
  (value - FREEZING_POINT_FAHRENHEIT) * FAHRENHEIT_TO_CELSIUS_RATIO
end

def ctof(value)
  (value * CELSIUS_TO_FAHRENHEIT_RATIO) + FREEZING_POINT_FAHRENHEIT
end